name: Maven CI/CD

on:
 push:
    branches: [ "master" ]
 pull_request:
    branches: [ "master" ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'zulu'
        cache: maven
    
    - name: Build project with Maven
      run: mvn -B package --file pom.xml
